apiVersion: v1
kind: Service
metadata:
  name: percy-eks-service
  namespace: percy-eks-namespace
  labels:
    app: percy-eks-app
spec:
  selector:
    app: percy-eks-app
  ports:
    - protocol: HTTP
      port: 8080
      targetPort: 8080
